# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - CenfoCinemasUI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build WebApp
        run: dotnet build ./5_WebApp/WebApp/WebApp.csproj --configuration Release

      - name: Publish WebApp
        run: dotnet publish ./5_WebApp/WebApp/WebApp.csproj -c Release -o "${{env.DOTNET_ROOT}}/mywebapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/mywebapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDA450B5889C4A9CAB7CCB4D889A1DA6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6664C715443F4E68A2CA5A944A300FAC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DBBE25D7A07472B88A3D6DEB0F31E60 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CenfoCinemasUI' 
          slot-name: 'Production'
          package: .
          